name: "Two column page (left sidebar)"
rows:
    - regions:
        - { name: "sidebar", span: 4 }
        - { name: "main", span: 8 }
template: "Ten24CMSPagesBundle::Pages\\Common\\two-column-left-pagetemplate.html.twig"