name: "Two column page (right sidebar)"
rows:
    - regions:
        - { name: "main", span: 8 }
        - { name: "sidebar", span: 4 }
template: "Ten24CMSPagesBundle::Pages\\Common\\two-column-right-pagetemplate.html.twig"