name: "Home"
context: "main"
types:
    - { name: Header, class: Kunstmaan\PagePartBundle\Entity\HeaderPagePart }
    - { name: Text, class: Kunstmaan\PagePartBundle\Entity\TextPagePart }
    - { name: Line, class: Kunstmaan\PagePartBundle\Entity\LinePagePart }
    - { name: Link, class: Kunstmaan\PagePartBundle\Entity\LinkPagePart }
    - { name: Image, class: Kunstmaan\MediaPagePartBundle\Entity\ImagePagePart }
    - { name: Download, class: Kunstmaan\MediaPagePartBundle\Entity\DownloadPagePart }
    - { name: Video, class: Kunstmaan\MediaPagePartBundle\Entity\VideoPagePart }

